create table US_elections_2018_unofficial (
    state varchar,
    county varchar,
    fips int,
    trump16 int,
    clinton16 int,
    otherpres16 int,
    romney12 int,
    obama12 int,
    otherpres12 int,
    demsen16 int,
    repsen16 int,
    othersen16 int,
    demhouse16 int,
    rephouse16 int,
    otherhouse16 int,
    demgov16 int,
    repgov16 int,
    othergov16 int,
    repgov14 int,
    demgov14 int,
    othergov14 int,
    total_population int,
    cvap int,
    white_pct decimal,
    black_pct decimal,
    hispanic_pct decimal,
    nonwhite_pct decimal,
    foreignborn_pct decimal,
    female_pct decimal,
    age29andunder_pct decimal,
    age65andolder_pct decimal,
    median_hh_inc int,
    clf_unemploy_pct decimal,
    lesshs_pct decimal,
    lesscollege_pct decimal,
    lesshs_whites_pct decimal,
    lesscollege_whites_pct decimal,
    rural_pct decimal,
    ruralurban_cc int
);

create table summary (
    state varchar,
    trump16 int,
    clinton16 int,
    otherpres16 int,
    insert_date varchar
);

copy US_elections_2018_unofficial (
    state,
    county,
    fips,
    trump16,
    clinton16,
    otherpres16,
    romney12,
    obama12,
    otherpres12,
    demsen16,
    repsen16,
    othersen16,
    demhouse16,
    rephouse16,
    otherhouse16,
    demgov16,
    repgov16,
    othergov16,
    repgov14,
    demgov14,
    othergov14,
    total_population,
    cvap,
    white_pct,
    black_pct,
    hispanic_pct,
    nonwhite_pct,
    foreignborn_pct,
    female_pct,
    age29andunder_pct,
    age65andolder_pct,
    median_hh_inc,
    clf_unemploy_pct,
    lesshs_pct,
    lesscollege_pct,
    lesshs_whites_pct,
    lesscollege_whites_pct,
    rural_pct,
    ruralurban_cc
) from '/var/lib/postgresql/csvs/election-context-2018.csv' 
    delimiter ',' 
    null 'NA'
    csv
    header;
